services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "3017:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*

